"""Add image_url to Marker model

Revision ID: 36c58f2884cd
Revises: b984086bb551
Create Date: 2026-09-10 18:42:31.543081

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36c58f2884cd"
down_revision: Union[str, Sequence[str], None] = "b984086bb551"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("marker", sa.Column("image_url", sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("marker", "image_url")
    # ### end Alembic commands ###
