from db.models import Address, Marker
from db.enums import MarkerCategory, MarkerUrgency, MarkerStatus

sample_markers = [
    Marker(
        position=[43.653226, -79.3831843],
        description="Large pothole reported near intersection; causes lane shifting at rush hour.",
        title="Pothole at King & Bay",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="100 King St W",
            city="Toronto",
            state="ON",
            postal_code="M5X 1A9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.70011, -79.4163],
        description="Overflowing bins attracting raccoons; needs cleanup.",
        title="Overflowing Bins at Park",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="200 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M4V 1R1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.65107, -79.347015],
        description="Frequent near-misses at poorly marked crosswalk.",
        title="Unsafe Crosswalk by Distillery",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="55 Mill St",
            city="Toronto",
            state="ON",
            postal_code="M5A 3C4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.761539, -79.411079],
        description="Graffiti on community center wall; request removal.",
        title="Graffiti at Community Center",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="2500 Yonge St",
            city="Toronto",
            state="ON",
            postal_code="M4P 2H7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.589045, -79.64412],
        description="Streetlight flickers and goes dark intermittently.",
        title="Faulty Streetlight Mississauga",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1 City Centre Dr",
            city="Mississauga",
            state="ON",
            postal_code="L5B 2T4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.25654, -79.8696],
        description="Illegal dumping spotted behind plaza; several black bags.",
        title="Illegal Dumping in Alley",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="500 Upper James St",
            city="Hamilton",
            state="ON",
            postal_code="L9C 2Y2",
            country="Canada",
        ),
    ),
    Marker(
        position=[45.421532, -75.697189],
        description="Bike lane blocked daily by delivery vans; needs enforcement.",
        title="Chronic Bike Lane Blocking",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="100 Elgin St",
            city="Ottawa",
            state="ON",
            postal_code="K1P 5K8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.463],
        description="Hydrant appears damaged; cap missing and slow leak observed.",
        title="Damaged Fire Hydrant",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="123 Runnymede Rd",
            city="Toronto",
            state="ON",
            postal_code="M6S 2Y2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6425662, -79.3870568],
        description="Pickpocket incident reported during evening crowd.",
        title="Pickpocketing Near CN Tower",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="301 Front St W",
            city="Toronto",
            state="ON",
            postal_code="M5V 2T6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.761, -79.319],
        description="Playground equipment loose bolt; child safety risk.",
        title="Loose Bolt on Slide",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="77 Lawrence Ave E",
            city="Toronto",
            state="ON",
            postal_code="M4N 1S5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.582],
        description="Storm drain clogged; pooling water after light rain.",
        title="Clogged Storm Drain",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="10 The Queensway",
            city="Toronto",
            state="ON",
            postal_code="M6R 1B1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.719, -79.466],
        description="Speeding on residential street; request speed bumps.",
        title="Speeding Hotspot",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="400 Eglinton Ave W",
            city="Toronto",
            state="ON",
            postal_code="M5N 1A2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.379],
        description="Sidewalk heaving causes tripping hazard near transit stop.",
        title="Heaved Sidewalk Slab",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="10 Queen St E",
            city="Toronto",
            state="ON",
            postal_code="M5C 1J3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6629, -79.3957],
        description="Loud parties past midnight on weekends.",
        title="Noise Complaints by Campus",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="27 Harbord St",
            city="Toronto",
            state="ON",
            postal_code="M5S 1G9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.645, -79.380],
        description="Suspicious activity near parking garage entrance reported twice.",
        title="Suspicious Loitering",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 Wellington St W",
            city="Toronto",
            state="ON",
            postal_code="M5V 3C7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.293],
        description="Beach litter after weekend; turtles sighted nearby.",
        title="Beach Litter Cleanup Needed",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1675 Lake Shore Blvd E",
            city="Toronto",
            state="ON",
            postal_code="M4L 3W6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.761, -79.23],
        description="Crossing signal timing too short for seniors.",
        title="Short Walk Signal",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1400 Victoria Park Ave",
            city="Toronto",
            state="ON",
            postal_code="M4A 2L8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.736, -79.608],
        description="Sinkhole forming near bus stop; cones placed.",
        title="Small Sinkhole Alert",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="7200 Airport Rd",
            city="Mississauga",
            state="ON",
            postal_code="L4T 2H5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.447, -80.488],
        description="Bike theft reported; CCTV may have captured suspect.",
        title="Bike Theft at Plaza",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="247 King St N",
            city="Waterloo",
            state="ON",
            postal_code="N2J 2Y8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.473, -80.542],
        description="Creek water appears cloudy; possible upstream construction runoff.",
        title="Cloudy Creek Water",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="5 Laurel Trail",
            city="Waterloo",
            state="ON",
            postal_code="N2J 3Z6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.256, -79.871],
        description="Crosswalk paint faded; drivers not yielding.",
        title="Faded Crosswalk Lines",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="12 Main St W",
            city="Hamilton",
            state="ON",
            postal_code="L8P 1H2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.589, -79.760],
        description="Stray dog seen roaming near school; appears friendly but lost.",
        title="Stray Dog Near School",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="3000 Argentia Rd",
            city="Mississauga",
            state="ON",
            postal_code="L5N 5P7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.544, -80.248],
        description="Broken bench slat; splinters reported.",
        title="Broken Park Bench",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="100 Woolwich St",
            city="Guelph",
            state="ON",
            postal_code="N1H 3T9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.464, -80.520],
        description="Overgrown vegetation obstructing path signs.",
        title="Overgrown Trail Signs",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 University Ave W",
            city="Waterloo",
            state="ON",
            postal_code="N2L 3G1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.392],
        description="Phone snatching reported; consider patrol.",
        title="Phone Snatch at Food Court",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="220 Yonge St",
            city="Toronto",
            state="ON",
            postal_code="M5B 2H1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.645, -79.410],
        description="Construction fencing leaning into sidewalk.",
        title="Leaning Construction Fence",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1200 King St W",
            city="Toronto",
            state="ON",
            postal_code="M6K 1G6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.700, -79.330],
        description="Street flooding after 10-minute shower indicates drainage issue.",
        title="Flash Flood Spot",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="999 O'Connor Dr",
            city="Toronto",
            state="ON",
            postal_code="M4B 2T5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.640, -79.380],
        description="Manhole cover rattles loudly when cars pass.",
        title="Noisy Manhole Cover",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 Bremner Blvd",
            city="Toronto",
            state="ON",
            postal_code="M5V 3L9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.654, -79.456],
        description="Fireworks after midnight violating bylaws.",
        title="Late-Night Fireworks",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="400 Dundas St W",
            city="Toronto",
            state="ON",
            postal_code="M5T 1G4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.718, -79.518],
        description="Stop sign knocked down after minor collision.",
        title="Downed Stop Sign",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="10 Weston Rd",
            city="Toronto",
            state="ON",
            postal_code="M6N 3P4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.789, -79.415],
        description="Car break-ins reported over two nights.",
        title="Car Break-in Cluster",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="5500 Yonge St",
            city="North York",
            state="ON",
            postal_code="M2N 5S3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.399],
        description="Food truck grease runoff into gutter.",
        title="Grease Runoff Concern",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="480 University Ave",
            city="Toronto",
            state="ON",
            postal_code="M5G 1V2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.776, -79.231],
        description="Playground fence missing a section.",
        title="Missing Fence Panel",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="45 Eglinton Square",
            city="Toronto",
            state="ON",
            postal_code="M1L 2K1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.747, -79.589],
        description="Traffic light stuck on flashing yellow intermittently.",
        title="Faulty Traffic Signal",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="500 Rexdale Blvd",
            city="Etobicoke",
            state="ON",
            postal_code="M9W 6K5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.371],
        description="Aggressive solicitation reported near subway entrance.",
        title="Aggressive Panhandling",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1 Queen St E",
            city="Toronto",
            state="ON",
            postal_code="M5C 2W5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.669, -79.393],
        description="Native plants trampled by shortcut; request signage.",
        title="Trampled Garden Beds",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="789 Yonge St",
            city="Toronto",
            state="ON",
            postal_code="M4W 2G8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.704, -79.398],
        description="Narrow bridge without guardrails; near-miss reported.",
        title="Bridge Without Guardrails",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1000 Avenue Rd",
            city="Toronto",
            state="ON",
            postal_code="M5P 2K2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.776, -79.335],
        description="Sidewalk snow/ice not cleared after storm.",
        title="Icy Sidewalk Stretch",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="220 Consumer Rd",
            city="Toronto",
            state="ON",
            postal_code="M2J 4R4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.650, -79.380],
        description="Lost child reported briefly; reunited—log for pattern monitoring.",
        title="Brief Lost Child Report",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="190 Bay St",
            city="Toronto",
            state="ON",
            postal_code="M5J 2J2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.431],
        description="Illegal scooter racing around midnight.",
        title="Late Scooter Racing",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1181 Dufferin St",
            city="Toronto",
            state="ON",
            postal_code="M6H 4C1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.648, -79.380],
        description="Loose overhead sign bracket on storefront awning.",
        title="Loose Awning Bracket",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="100 Adelaide St W",
            city="Toronto",
            state="ON",
            postal_code="M5H 1S3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.662, -79.379],
        description="Tree roots lifting curb and cracking asphalt.",
        title="Tree Root Uplift",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="250 College St",
            city="Toronto",
            state="ON",
            postal_code="M5T 1R5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.705, -79.329],
        description="Garbage scattered by wind after collection missed.",
        title="Missed Garbage Pickup",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="999 Victoria Park Ave",
            city="Toronto",
            state="ON",
            postal_code="M4B 2H5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.590, -79.644],
        description="Repeated porch thefts; camera footage available.",
        title="Package Theft Pattern",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="10 Burnhamthorpe Rd W",
            city="Mississauga",
            state="ON",
            postal_code="L5B 3Y5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.743, -79.258],
        description="School crossing guard absent 3 days this week.",
        title="Crossing Guard Absence",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="2300 Lawrence Ave E",
            city="Scarborough",
            state="ON",
            postal_code="M1P 2R2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.693, -79.287],
        description="Flooded underpass after rainfall; cars turning around.",
        title="Flooded Underpass",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="300 Coxwell Ave",
            city="Toronto",
            state="ON",
            postal_code="M4L 3B6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.756, -79.518],
        description="Uneven steps at library entrance.",
        title="Uneven Library Steps",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="789 Jane St",
            city="Toronto",
            state="ON",
            postal_code="M6N 4C4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.630, -79.722],
        description="Nighttime drag racing; request speed cameras.",
        title="Drag Racing Reports",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="5 Steeles Ave E",
            city="Brampton",
            state="ON",
            postal_code="L6W 1B3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.648, -79.3805],
        description="Rats seen near storm drain; bait requested.",
        title="Rodent Sightings",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="111 Richmond St W",
            city="Toronto",
            state="ON",
            postal_code="M5H 2G4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.642, -79.374],
        description="Pocket park lights out; very dark after 8pm.",
        title="Park Lights Out",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="25 The Esplanade",
            city="Toronto",
            state="ON",
            postal_code="M5E 1W5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.670, -79.385],
        description="Bus shelter glass shattered; shards remaining.",
        title="Shattered Bus Shelter",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="700 Bloor St W",
            city="Toronto",
            state="ON",
            postal_code="M6G 1L5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.644, -79.395],
        description="Street tree newly planted; needs watering schedule.",
        title="New Tree Needs Water",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="180 University Ave",
            city="Toronto",
            state="ON",
            postal_code="M5H 0A2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.409],
        description="Abandoned bicycle locked to post for months.",
        title="Abandoned Bicycle",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="500 Dupont St",
            city="Toronto",
            state="ON",
            postal_code="M6G 1Y7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.767, -79.413],
        description="Alley lights flicker, potential wiring issue.",
        title="Flickering Alley Lights",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 Finch Ave W",
            city="North York",
            state="ON",
            postal_code="M2R 1M8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.645, -79.380],
        description="Repeated wallet thefts reported at market stalls.",
        title="Market Wallet Thefts",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="93 Front St E",
            city="Toronto",
            state="ON",
            postal_code="M5E 1C3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.649, -79.468],
        description="Oil sheen visible on puddles near garage.",
        title="Oil Sheen on Pavement",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="2 Keele St",
            city="Toronto",
            state="ON",
            postal_code="M6N 3C9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.662, -79.332],
        description="Missing tactile paving at curb cut.",
        title="Missing Tactile Paving",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="1200 Gerrard St E",
            city="Toronto",
            state="ON",
            postal_code="M4L 1Y7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.690, -79.297],
        description="Erosion along trail edge; posts leaning.",
        title="Trail Erosion",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="23 Taylor Creek Dr",
            city="Toronto",
            state="ON",
            postal_code="M4A 2S6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.778, -79.233],
        description="Suspicious door-to-door activity reported.",
        title="Suspicious Door Knockers",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1201 Ellesmere Rd",
            city="Scarborough",
            state="ON",
            postal_code="M1P 4Y1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.642, -79.575],
        description="Backyard fire smoke complaints; bylaw notice requested.",
        title="Backyard Fire Smoke",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="15 The Queensway",
            city="Toronto",
            state="ON",
            postal_code="M8Y 1J7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.755, -79.432],
        description="Crosswalk button unresponsive intermittently.",
        title="Unresponsive Crosswalk Button",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="4900 Dufferin St",
            city="North York",
            state="ON",
            postal_code="M3H 5T4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.654, -79.380],
        description="Delivery trucks idling; air quality complaints.",
        title="Truck Idling Complaints",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="65 Queen St W",
            city="Toronto",
            state="ON",
            postal_code="M5H 2M5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.661, -79.476],
        description="Children crossing mid-block; request signage.",
        title="Mid-block Crossing Risk",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1000 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M6E 1A1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.395],
        description="Cracked glass canopy panel (not fallen).",
        title="Cracked Canopy Glass",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="200 Bloor St W",
            city="Toronto",
            state="ON",
            postal_code="M5S 1T8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.700, -79.416],
        description="Needles found in shrub area; request safe disposal.",
        title="Discarded Needles",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="10 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M4V 1K6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.384],
        description="Unauthorized street vendors blocking pedestrian flow.",
        title="Unlicensed Street Vendors",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1 Dundas St W",
            city="Toronto",
            state="ON",
            postal_code="M5G 1Z3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.700, -79.560],
        description="Guardrail dented after fender-bender.",
        title="Dented Guardrail",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="500 The West Mall",
            city="Etobicoke",
            state="ON",
            postal_code="M9C 1E9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.669, -79.402],
        description="Public fountain water appears green; filter issue suspected.",
        title="Greenish Fountain Water",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="789 Avenue Rd",
            city="Toronto",
            state="ON",
            postal_code="M5P 2K1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.776, -79.3355],
        description="Jaywalking near transit hub; need barrier or signage.",
        title="Jaywalking Near Hub",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="250 Sheppard Ave E",
            city="North York",
            state="ON",
            postal_code="M2N 6M9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.773, -79.498],
        description="Faded lane markings causing confusion at merge.",
        title="Faded Merge Markings",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1000 Wilson Ave",
            city="North York",
            state="ON",
            postal_code="M3K 1G2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.657, -79.378],
        description="Pocket pick incidents during events; increased patrol requested.",
        title="Event Pickpocketing Pattern",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="40 Bay St",
            city="Toronto",
            state="ON",
            postal_code="M5J 2X2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.711, -79.279],
        description="Tree limb broken and hanging over sidewalk.",
        title="Hanging Tree Limb",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="3000 Danforth Ave",
            city="Toronto",
            state="ON",
            postal_code="M4C 1M7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.662, -79.442],
        description="Culvert partially blocked by debris.",
        title="Debris in Culvert",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="25 Caledonia Rd",
            city="Toronto",
            state="ON",
            postal_code="M6E 4S3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.650, -79.377],
        description="Metal grate missing two bolts; rattles.",
        title="Loose Metal Grate",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="33 Yonge St",
            city="Toronto",
            state="ON",
            postal_code="M5E 1G4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.381],
        description="E-bikes speeding through pedestrian plaza.",
        title="E-bikes in Pedestrian Zone",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1 Toronto St",
            city="Toronto",
            state="ON",
            postal_code="M5C 2V6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.648, -79.397],
        description="Restaurant trash stored on sidewalk overnight.",
        title="Restaurant Trash on Sidewalk",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="120 Spadina Ave",
            city="Toronto",
            state="ON",
            postal_code="M5V 2L1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.2935],
        description="Beach lifeguard chair damaged.",
        title="Damaged Lifeguard Chair",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1300 Lake Shore Blvd E",
            city="Toronto",
            state="ON",
            postal_code="M4L 1C8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.700, -79.3305],
        description="Graffiti tagged on sound barrier walls.",
        title="Sound Barrier Graffiti",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="123 Don Mills Rd",
            city="Toronto",
            state="ON",
            postal_code="M3B 2W2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.640, -79.389],
        description="Uncovered utility trench; temporary fencing only.",
        title="Open Utility Trench",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="25 York St",
            city="Toronto",
            state="ON",
            postal_code="M5J 2V5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.651, -79.380],
        description="Reports of counterfeit bills at nearby shops.",
        title="Counterfeit Bills Reports",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="111 Queen St W",
            city="Toronto",
            state="ON",
            postal_code="M5H 2N1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.651, -79.407],
        description="Stormwater pond aerator not running.",
        title="Aerator Not Operating",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="789 Bathurst St",
            city="Toronto",
            state="ON",
            postal_code="M5S 1Z5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.671, -79.466],
        description="Playground gate latch broken.",
        title="Broken Gate Latch",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="2000 Eglinton Ave W",
            city="York",
            state="ON",
            postal_code="M6E 2J4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.699, -79.292],
        description="Sidewalk closure with no detour signage.",
        title="No Detour Signage",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="3000 Gerrard St E",
            city="Scarborough",
            state="ON",
            postal_code="M1N 1Y8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.640, -79.3805],
        description="Pedestrians feeding gulls; mess accumulating.",
        title="Feeding Gulls Mess",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="250 Front St W",
            city="Toronto",
            state="ON",
            postal_code="M5V 3G5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.655, -79.380],
        description="Aggressive dog off-leash in on-leash area.",
        title="Aggressive Off-Leash Dog",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="80 Dundas St E",
            city="Toronto",
            state="ON",
            postal_code="M5B 2P5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.675, -79.412],
        description="Skate park lights out after 9pm curfew time.",
        title="Skate Park Lights Out",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="750 Davenport Rd",
            city="Toronto",
            state="ON",
            postal_code="M6G 2L3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.689, -79.460],
        description="Repeated catalytic converter thefts overnight.",
        title="Catalytic Converter Thefts",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="123 Caledonia Park Rd",
            city="Toronto",
            state="ON",
            postal_code="M6E 4S9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.367],
        description="Sewage smell near storm drain; investigation requested.",
        title="Sewage Odor Complaint",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="160 Jarvis St",
            city="Toronto",
            state="ON",
            postal_code="M5B 2J4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.704, -79.397],
        description="Blind corner hedge overgrowth; trim requested.",
        title="Blind Corner Hedge",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="50 Oriole Pkwy",
            city="Toronto",
            state="ON",
            postal_code="M5P 2H8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.645, -79.379],
        description="Loose handrail on stairs to lower concourse.",
        title="Loose Stair Handrail",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="65 Front St W",
            city="Toronto",
            state="ON",
            postal_code="M5J 1E6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.668, -79.306],
        description="Paint spilled on bike lane creating slick area.",
        title="Paint Spill in Bike Lane",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="123 Jones Ave",
            city="Toronto",
            state="ON",
            postal_code="M4M 3H2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.713, -79.465],
        description="School zone sign twisted 90 degrees.",
        title="Twisted School Zone Sign",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="450 Oakwood Ave",
            city="York",
            state="ON",
            postal_code="M6E 2W3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.606, -79.497],
        description="Boardwalk plank replaced unevenly causing trip hazard.",
        title="Uneven Boardwalk Plank",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="130 Lake Shore Dr",
            city="Etobicoke",
            state="ON",
            postal_code="M8V 1A1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.771, -79.413],
        description="Night market generators too close to residences.",
        title="Noisy Night Market",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="15 Cummer Ave",
            city="North York",
            state="ON",
            postal_code="M2M 2E5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.654, -79.435],
        description="Construction dust without water suppression.",
        title="Construction Dust Issue",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1017 Bloor St W",
            city="Toronto",
            state="ON",
            postal_code="M6H 1M1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.667, -79.373],
        description="Alley blocked by illegally parked vehicles.",
        title="Blocked Alley Access",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="250 Church St",
            city="Toronto",
            state="ON",
            postal_code="M5B 1Z2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.680, -79.300],
        description="Open electrical box near bus stop.",
        title="Open Electrical Box",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1400 Danforth Ave",
            city="Toronto",
            state="ON",
            postal_code="M4J 1N2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.699, -79.429],
        description="Collapsed catch basin grate leaving gap.",
        title="Collapsed Catch Basin",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.PENDING,
        address=Address(
            street="777 Eglinton Ave W",
            city="Toronto",
            state="ON",
            postal_code="M5N 1E9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.706, -79.399],
        description="Skunk sightings near garbage storage.",
        title="Skunk Sightings",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="300 Lonsdale Rd",
            city="Toronto",
            state="ON",
            postal_code="M4V 1X4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.664, -79.382],
        description="Pickpocket warning sign requested after incidents.",
        title="Request Warning Signage",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="100 Gerrard St E",
            city="Toronto",
            state="ON",
            postal_code="M5B 1G7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.720, -79.344],
        description="Playfield lights staying on past scheduled time.",
        title="Lights On After Hours",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="45 Overlea Blvd",
            city="Toronto",
            state="ON",
            postal_code="M4H 1C3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.675, -79.414],
        description="Loose storm sewer cover clanking loudly.",
        title="Clanking Sewer Cover",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="999 Christie St",
            city="Toronto",
            state="ON",
            postal_code="M6G 3J7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.772, -79.292],
        description="Air quality complaints from auto shop spray.",
        title="Auto Shop Spray Paint Odor",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="2000 Victoria Park Ave",
            city="Toronto",
            state="ON",
            postal_code="M1R 1V2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.648, -79.371],
        description="Theft from unlocked cars; outreach for prevention needed.",
        title="Unlocked Car Thefts",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="20 Adelaide St E",
            city="Toronto",
            state="ON",
            postal_code="M5C 2T6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.660, -79.346],
        description="Bridge expansion joint exposed; cyclists at risk.",
        title="Exposed Expansion Joint",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="500 Parliament St",
            city="Toronto",
            state="ON",
            postal_code="M4X 1P3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.645, -79.3808],
        description="Sidewalk vendor grease spill—slippery area.",
        title="Grease Spill on Walk",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="222 Bay St",
            city="Toronto",
            state="ON",
            postal_code="M5K 1E7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.665, -79.410],
        description="Railing missing on footbridge.",
        title="Missing Footbridge Railing",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="100 Christie St",
            city="Toronto",
            state="ON",
            postal_code="M6G 3B5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.652, -79.381],
        description="Tourists repeatedly targeted by fake ticket sellers.",
        title="Fake Ticket Sellers",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1 Front St E",
            city="Toronto",
            state="ON",
            postal_code="M5E 1B2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.710, -79.398],
        description="Park irrigation head spraying sidewalk.",
        title="Irrigation Overspray",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="500 Eglinton Ave W",
            city="Toronto",
            state="ON",
            postal_code="M5N 1A5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.658, -79.380],
        description="Escalator intermittently stops; crowding ensues.",
        title="Intermittent Escalator",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="65 Front St W",
            city="Toronto",
            state="ON",
            postal_code="M5J 1E6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.640, -79.382],
        description="Delivery bikes riding against traffic in lane.",
        title="Wrong-way Delivery Bikes",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="123 Lower Simcoe St",
            city="Toronto",
            state="ON",
            postal_code="M5J 3A6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.679, -79.431],
        description="Dumpster enclosure gate broken; wind-blown trash.",
        title="Broken Dumpster Gate",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="50 Winona Dr",
            city="Toronto",
            state="ON",
            postal_code="M6G 3Z9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.706, -79.344],
        description="Stop bar paint missing at intersection.",
        title="Missing Stop Bar Paint",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="500 Don Mills Rd",
            city="Toronto",
            state="ON",
            postal_code="M3C 1L1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.647, -79.368],
        description="Scam QR code stickers placed on meters.",
        title="Fake QR Code Stickers",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 King St E",
            city="Toronto",
            state="ON",
            postal_code="M5A 1J7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.618, -79.506],
        description="Shoreline litter after weekend picnic groups.",
        title="Shoreline Litter",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="222 Lake Shore Dr",
            city="Etobicoke",
            state="ON",
            postal_code="M8V 2A8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.669, -79.393],
        description="Fence leaning into sidewalk due to soil washout.",
        title="Leaning Fence",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="20 Balmoral Ave",
            city="Toronto",
            state="ON",
            postal_code="M4V 1J4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.643, -79.427],
        description="Pedestrian signal head rotated away from crossing.",
        title="Rotated Signal Head",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="1300 King St W",
            city="Toronto",
            state="ON",
            postal_code="M6K 1G8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.652, -79.384],
        description="Reports of pocket knives brandished in argument; no injuries.",
        title="Altercation with Knife",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="100 Richmond St W",
            city="Toronto",
            state="ON",
            postal_code="M5H 3K6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.357],
        description="Tree well missing grate; ankle hazard.",
        title="Missing Tree Grate",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 Sherbourne St",
            city="Toronto",
            state="ON",
            postal_code="M5A 3Z5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.679, -79.294],
        description="Graffiti on bridge abutment.",
        title="Bridge Graffiti",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="100 Woodbine Ave",
            city="Toronto",
            state="ON",
            postal_code="M4L 2A2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.744, -79.587],
        description="Hazardous materials stored outdoors without cover.",
        title="Uncovered Hazardous Materials",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="100 Carlingview Dr",
            city="Etobicoke",
            state="ON",
            postal_code="M9W 5E7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.664, -79.383],
        description="Reports of phone scammers posing as city officials.",
        title="Phone Scam Reports",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="40 Elizabeth St",
            city="Toronto",
            state="ON",
            postal_code="M5G 2C4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.710, -79.562],
        description="Playground surface depressions collecting water.",
        title="Play Surface Depressions",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 The East Mall",
            city="Etobicoke",
            state="ON",
            postal_code="M9B 6E2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.319],
        description="Recycling contamination—bags full of food waste.",
        title="Recycling Contamination",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="500 Greenwood Ave",
            city="Toronto",
            state="ON",
            postal_code="M4J 4A7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.647, -79.402],
        description="Scooter collision near streetcar stop; no injuries reported.",
        title="Minor Scooter Collision",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="520 Spadina Ave",
            city="Toronto",
            state="ON",
            postal_code="M5S 2H3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.772, -79.257],
        description="Crosswalk lines newly installed; monitor compliance.",
        title="New Crosswalk Monitoring",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1900 Lawrence Ave E",
            city="Toronto",
            state="ON",
            postal_code="M1R 2Y5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.663, -79.425],
        description="Coyote sighting near ravine; appears healthy.",
        title="Coyote Sighting",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="30 Winona Dr",
            city="Toronto",
            state="ON",
            postal_code="M6G 3Z7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.642, -79.389],
        description="Elevator reliability issues reported by residents.",
        title="Elevator Reliability Issues",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="10 Navy Wharf Ct",
            city="Toronto",
            state="ON",
            postal_code="M5V 3V2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.662, -79.377],
        description="Street artist obstructing fire exit with setup.",
        title="Blocked Fire Exit",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="100 Elm St",
            city="Toronto",
            state="ON",
            postal_code="M5G 1G5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.647, -79.370],
        description="Stolen bike recovered by resident; awaiting pickup.",
        title="Recovered Stolen Bike",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="60 Lombard St",
            city="Toronto",
            state="ON",
            postal_code="M5C 3M9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.676, -79.420],
        description="Storm-damaged tree leaning toward road.",
        title="Storm-Leaning Tree",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="700 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M6C 1B1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.698, -79.394],
        description="Sewer backflow noticed in basement units nearby.",
        title="Sewer Backflow Reports",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="200 Broadway Ave",
            city="Toronto",
            state="ON",
            postal_code="M4P 1V9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.651, -79.378],
        description="Skateboarders grinding new handrails; request signage.",
        title="Handrail Grinding",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="55 Wellington St W",
            city="Toronto",
            state="ON",
            postal_code="M5V 3P5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.704, -79.3995],
        description="Bus stop pad settling causing water pooling.",
        title="Settled Bus Stop Pad",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="290 Oriole Pkwy",
            city="Toronto",
            state="ON",
            postal_code="M5P 2H1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.760, -79.411],
        description="Blocked sightline at intersection by parked van.",
        title="Blocked Sightline",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="10 Beecroft Rd",
            city="North York",
            state="ON",
            postal_code="M2N 5W7",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.673, -79.321],
        description="Community garden vandalized; plants uprooted.",
        title="Community Garden Vandalism",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="500 Coxwell Ave",
            city="Toronto",
            state="ON",
            postal_code="M4J 1R8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.686, -79.393],
        description="Hydro pole leaning slightly after vehicle strike.",
        title="Leaning Hydro Pole",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="300 Roehampton Ave",
            city="Toronto",
            state="ON",
            postal_code="M4P 1S2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.640, -79.379],
        description="Marina fuel sheen observed; notify harbor master.",
        title="Fuel Sheen at Marina",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="539 Queens Quay W",
            city="Toronto",
            state="ON",
            postal_code="M5V 2G3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.654, -79.383],
        description="Unattended luggage reported in food court; cleared by security.",
        title="Unattended Luggage Report",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="220 Yonge St",
            city="Toronto",
            state="ON",
            postal_code="M5B 2H1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.668, -79.395],
        description="Storm grate missing bolts—could dislodge.",
        title="Loose Storm Grate",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="90 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M4V 1N5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.653, -79.3715],
        description="Public washroom out of service; lineups large.",
        title="Washroom Out of Service",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1 Queen St E",
            city="Toronto",
            state="ON",
            postal_code="M5C 2W5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.7005, -79.4165],
        description="Dead raccoon on roadway; removal requested.",
        title="Roadkill Removal",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="15 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M4V 1K6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6505, -79.382],
        description="Unauthorized drone flights near tall buildings reported.",
        title="Unauthorized Drone Flights",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="88 Queens Quay W",
            city="Toronto",
            state="ON",
            postal_code="M5J 0B8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6765, -79.2938],
        description="Broken shower at beach change room.",
        title="Beach Facility Repair",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="1675 Lake Shore Blvd E",
            city="Toronto",
            state="ON",
            postal_code="M4L 3W6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6715, -79.4662],
        description="Curb ramp too steep for wheelchairs; complaint filed.",
        title="Steep Curb Ramp",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="2100 Eglinton Ave W",
            city="York",
            state="ON",
            postal_code="M6E 2K3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.659, -79.380],
        description="Overflow event at combined sewer outfall suspected.",
        title="CSO Overflow Suspected",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.PENDING,
        address=Address(
            street="30 Yonge St",
            city="Toronto",
            state="ON",
            postal_code="M5E 1X8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.695, -79.284],
        description="Street hockey creating noise complaints; outreach requested.",
        title="Street Hockey Complaints",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1500 Danforth Ave",
            city="Toronto",
            state="ON",
            postal_code="M4J 5B5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.707, -79.398],
        description="Parking meter not accepting credit cards.",
        title="Parking Meter Card Failure",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="350 Eglinton Ave W",
            city="Toronto",
            state="ON",
            postal_code="M5N 1A2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6625, -79.3795],
        description="Trip hazard from protruding rebar on plaza edge.",
        title="Protruding Rebar",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="230 College St",
            city="Toronto",
            state="ON",
            postal_code="M5T 1R2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6402, -79.3802],
        description="Boat horns late at night exceeding noise limits.",
        title="Marina Noise After Hours",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="7 Queens Quay W",
            city="Toronto",
            state="ON",
            postal_code="M5J 2H3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.7008, -79.3308],
        description="Caged shopping carts abandoned on sidewalk.",
        title="Abandoned Shopping Carts",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="75 Don Mills Rd",
            city="Toronto",
            state="ON",
            postal_code="M3C 2E9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6865, -79.3933],
        description="Exposed rebar on retaining wall.",
        title="Exposed Retaining Wall Rebar",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="250 Roehampton Ave",
            city="Toronto",
            state="ON",
            postal_code="M4P 1R9",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6761, -79.3579],
        description="Milky discharge seen in creek; source unknown.",
        title="Milky Creek Discharge",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.CRITICAL,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="150 Sherbourne St",
            city="Toronto",
            state="ON",
            postal_code="M5A 2R6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6595, -79.3807],
        description="Skylight panel cracked in atrium.",
        title="Cracked Atrium Skylight",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.PENDING,
        address=Address(
            street="25 King St W",
            city="Toronto",
            state="ON",
            postal_code="M5L 2A1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6408, -79.3799],
        description="Boardwalk rail missing a baluster.",
        title="Missing Baluster on Rail",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="235 Queens Quay W",
            city="Toronto",
            state="ON",
            postal_code="M5J 2G8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6712, -79.4668],
        description="Dumpster overfilled; birds spreading trash.",
        title="Overfilled Dumpster",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1990 Eglinton Ave W",
            city="York",
            state="ON",
            postal_code="M6E 2J3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6535, -79.385],
        description="Street performer amplifier too loud; crowd spilling into roadway.",
        title="Amplified Street Performance",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="333 Bay St",
            city="Toronto",
            state="ON",
            postal_code="M5H 2R2",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.661, -79.378],
        description="Loose paving stone at fountain edge.",
        title="Loose Paving Stone",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="110 Elizabeth St",
            city="Toronto",
            state="ON",
            postal_code="M5G 1P5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6768, -79.2932],
        description="Beach access ramp handrail wobbly.",
        title="Wobbly Ramp Handrail",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="1700 Lake Shore Blvd E",
            city="Toronto",
            state="ON",
            postal_code="M4L 3W6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.702, -79.420],
        description="Storm siren test failed per residents; verify.",
        title="Storm Siren Test Failure",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="50 Glen Cedar Rd",
            city="Toronto",
            state="ON",
            postal_code="M6C 3G4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.680, -79.428],
        description="Traffic island sign sheared off.",
        title="Missing Traffic Island Sign",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="200 Oakwood Ave",
            city="York",
            state="ON",
            postal_code="M6E 2V4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.650, -79.360],
        description="Reports of counterfeit parking passes on dashboards.",
        title="Counterfeit Parking Passes",
        category=MarkerCategory.CRIME,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="150 Sherbourne St",
            city="Toronto",
            state="ON",
            postal_code="M5A 2R6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.699, -79.3302],
        description="Bats roosting in gazebo; public concerned.",
        title="Bat Roost in Gazebo",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="100 Don Mills Rd",
            city="Toronto",
            state="ON",
            postal_code="M3B 2W1",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.7065, -79.3998],
        description="Fallen banner tangled in power lines.",
        title="Banner in Power Lines",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="360 Eglinton Ave W",
            city="Toronto",
            state="ON",
            postal_code="M5N 1A3",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6406, -79.3811],
        description="Deck boards splintering near benches.",
        title="Splintering Deck Boards",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="201 Queens Quay W",
            city="Toronto",
            state="ON",
            postal_code="M5J 2Y5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6718, -79.4665],
        description="Raccoon-proof bins needed; lids missing.",
        title="Missing Bin Lids",
        category=MarkerCategory.ENVIRONMENT,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="2050 Eglinton Ave W",
            city="York",
            state="ON",
            postal_code="M6E 2J4",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6532, -79.3832],
        description="Emergency exit light not functioning.",
        title="Exit Light Not Working",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.HIGH,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="100 Bay St",
            city="Toronto",
            state="ON",
            postal_code="M5J 2N8",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.7002, -79.4162],
        description="Request for sharps container installation.",
        title="Request Sharps Container",
        category=MarkerCategory.OTHER,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.PENDING,
        address=Address(
            street="20 St Clair Ave W",
            city="Toronto",
            state="ON",
            postal_code="M4V 1L5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6762, -79.2931],
        description="Boardwalk edge rope frayed.",
        title="Frayed Boardwalk Rope",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.IN_PROGRESS,
        address=Address(
            street="1750 Lake Shore Blvd E",
            city="Toronto",
            state="ON",
            postal_code="M4L 3W6",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6518, -79.3819],
        description="Unauthorized buskers blocking accessibility ramp.",
        title="Buskers Block Access Ramp",
        category=MarkerCategory.SAFETY,
        urgency=MarkerUrgency.MEDIUM,
        status=MarkerStatus.PENDING,
        address=Address(
            street="55 Wellington St W",
            city="Toronto",
            state="ON",
            postal_code="M5V 3P5",
            country="Canada",
        ),
    ),
    Marker(
        position=[43.6621, -79.3792],
        description="Overflowing fountain basin due to clogged filter.",
        title="Clogged Fountain Filter",
        category=MarkerCategory.INFRASTRUCTURE,
        urgency=MarkerUrgency.LOW,
        status=MarkerStatus.RESOLVED,
        address=Address(
            street="230 College St",
            city="Toronto",
            state="ON",
            postal_code="M5T 1R2",
            country="Canada",
        ),
    ),
    Marker(
      position=[43.78472822909501, -79.1861080766575],
      description="Orion, Jayden, Kobe are at UTSC!",
      title="Hack the Valley Event",
      category=MarkerCategory.CRIME,
      urgency=MarkerUrgency.LOW,
      status=MarkerStatus.PENDING,
      address=Address(
          street="123 Campus Rd",
          city="Toronto",
          state="ON",
          postal_code="M1C 1A4",
          country="Canada",
      ),
    ),
]
